name: publish-to-npm
run-name: ${{ github.actor }} is publishing to npm
on:
  workflow_dispatch:
    inputs:
      bump_level:
        description: type of version bump
        type: choice
        default: patch
        required: true
        options:
          - patch
          - minor
          - major
          - custom (use custom_bump_level)
      custom_bump_level:
        description: version to bump to
        type: string

jobs:
  build-and-publish:
    name: build and publish package
    runs-on: ubuntu-latest
    steps:
      - if: ${{ startsWith(inputs.bump_level, 'custom') && inputs.custom_bump_level == '' }}
        run: "echo 'custom version indicated but not set' && exit 1"
      - uses: determined-ai/publish-to-npm-action/.github/workflows/publish-to-npm@v4
        with:
          bump_level: ${{ startsWith(inputs.bump_level, 'custom') && inputs.custom_bump_level || inputs.bump_level }}
          npm_token: ${{ secrets.NPM_CLASSIC_TOKEN }}
